(async () => {

// Obtain data from main process
var data = await window.getData();

// Get HTML elements
var startButton = document.getElementById("start-button");
var ipField = document.getElementById("server-address");
var passwordField = document.getElementById("server-password");
var saveButton = document.getElementById("save-button");
var nameHeader = document.getElementById("game-name");
 
// Format the game name
nameHeader.innerHTML = data.gameName;
nameHeader.style.color = data.color;
nameHeader.style.textShadow = "2px 2px 4px " + data.color + "88"; 

// Insert starting values into fields
ipField.value = data.ipAddress;
passwordField.value = data.password;

// Disabling the save button if fields are empty

// Assign event listeners to the buttons
document.getElementById("return-button").addEventListener("click", () => window.menuTransfer("main menu"));
startButton.addEventListener("click", () => window.menuTransfer("launch"));

saveButton.addEventListener("click", () => {
    // Update the data object
    data.ipAddress = ipField.value;
    data.password = passwordField.value;

    // Send it to main process
    window.setGameData(data);
});



/* Generated by ChatGPT */

function createParticles() {
    for (let i = 0; i < 20; i++) {
        let particle = document.createElement("div");
        particle.classList.add("particle");
        document.body.appendChild(particle);
        particle.style.left = `${Math.random() * 100}vw`;
        particle.style.top = `${Math.random() * 100}vh`;
        particle.style.animationDuration = `${3 + Math.random() * 5}s`;
        particle.style.backgroundColor = data.color + "88";
    }
}

createParticles();

})();
