// Get HTML elements
var startButton = document.getElementById("start-button");

// Assign event listeners to the buttons
document.getElementById("return-button").addEventListener("click", () => window.menuTransfer("main menu"));
startButton.addEventListener("click", () => window.menuTransfer("launch"));



/* Generated by ChatGPT */

function createParticles() {
    for (let i = 0; i < 20; i++) {
        let particle = document.createElement("div");
        particle.classList.add("particle");
        document.body.appendChild(particle);
        particle.style.left = `${Math.random() * 100}vw`;
        particle.style.top = `${Math.random() * 100}vh`;
        particle.style.animationDuration = `${3 + Math.random() * 5}s`;
    }
}

createParticles();
