(async () => {

// Obtain data from main process
var data = await window.getData();

// Get HTML elements
var startButton = document.getElementById("start-button");
var ipField = document.getElementById("server-address");
var passwordField = document.getElementById("server-password");
var nameField = document.getElementById("game-name-input");
var colorField = document.getElementById("signature-color");
var saveButton = document.getElementById("save-button");
var nameHeader = document.getElementById("game-name");

// Format the game name
function formatGameName() {
    nameHeader.innerHTML = data.gameName;
    nameHeader.style.color = data.color;
    nameHeader.style.textShadow = "2px 2px 4px " + data.color + "88";
}
formatGameName();

// Insert starting values into fields
ipField.value = data.ipAddress;
passwordField.value = data.password;
nameField.value = data.gameName;
colorField.value = data.color;

// Assign event listeners to the buttons
document.getElementById("return-button").addEventListener("click", () => window.menuTransfer("main menu"));
startButton.addEventListener("click", () => window.menuTransfer("launch"));

saveButton.addEventListener("click", () => {
    // Update the data object
    data.ipAddress = ipField.value;
    data.password = passwordField.value;
    data.gameName = nameField.value;
    data.color = colorField.value;

    // Send it to main process
    window.setGameData(data);

    // Update the button and particle colors and text
    formatGameName();
    document.querySelectorAll(".particle").forEach((particle) => particle.style.backgroundColor = data.color + "88");
});


/* Generated by ChatGPT */

function createParticles() {
    for (let i = 0; i < 20; i++) {
        let particle = document.createElement("div");
        particle.classList.add("particle");
        document.body.appendChild(particle);
        particle.style.left = `${Math.random() * 100}vw`;
        particle.style.top = `${Math.random() * 100}vh`;
        particle.style.animationDuration = `${3 + Math.random() * 5}s`;
        particle.style.backgroundColor = data.color + "88";
    }
}

createParticles();

})();