/* Generated by ChatGPT */
function createParticles() {
    const particleCount = 50;
    for (let i = 0; i < particleCount; i++) {
        const particle = document.createElement("div");
        particle.classList.add("particle");
        document.body.appendChild(particle);
        // Position the particle randomly across the viewport
        particle.style.left = Math.random() * 100 + "vw";
        particle.style.top = Math.random() * 100 + "vh";
        // Set a random size between 2px and 6px for variety
        const size = Math.random() * 4 + 2;
        particle.style.width = size + "px";
        particle.style.height = size + "px";
        // Randomize the animation duration (between 3 and 8 seconds) and delay
        const duration = 3 + Math.random() * 5;
        particle.style.animationDuration = duration + "s";
        particle.style.animationDelay = Math.random() * duration + "s";
    }
}
createParticles();
