// Helper function
// Generated using ChatGPT
function toDisplayName(programmingName) {
    // Replace hyphens or underscores with spaces
    let displayName = programmingName.replace(/[-_]/g, ' ');
    
    // Capitalize the first letter
    displayName = displayName.charAt(0).toUpperCase() + displayName.slice(1);
    
    return displayName;
}

// Module info class
class moduleInfo {
    constructor(name, extensions) {
        this.name = name;
        this.extensions = extensions;
    }
}

// Dynamically generate list of checkbox options
async function generateOptions() {
    // Obtain data
    let moduleList = await window.getModuleList();
    let selectedModules = await window.getSelectedModules(window.gameName);
    let checkboxList = document.getElementById("checkbox-list");

    // Generating the checklist
    for (i of moduleList) {
        // Module option div
        let moduleDiv = document.createElement("div");
        moduleDiv.setAttribute("class", "main-option-group");

        // Checkbox
        let moduleCheckbox = document.createElement("input");
        moduleCheckbox.type = "checkbox";
        moduleCheckbox.setAttribute("class", "main-option");
        moduleCheckbox.id = i.name;

        moduleDiv.appendChild(moduleCheckbox);
        moduleCheckbox.insertAdjacentText('afterend', toDisplayName(i.name));

        // Check if the module has extensions
        if (i.extensions.length > 0) {
            // Div for extensions
            let extensionDiv = document.createElement("div");
            extensionDiv.setAttribute("class", "sub-options-group");

            // Checkboxes for extensions
            for (j of i.extensions) {
                let extensionCheckbox = document.createElement("input");
                extensionCheckbox.type = "checkbox";
                extensionCheckbox.setAttribute("class", "sub-option");
                extensionCheckbox.disabled = true;
                extensionCheckbox.id = i.name + ":" + j;

                extensionDiv.appendChild(extensionCheckbox);
                extensionCheckbox.insertAdjacentText('afterend', toDisplayName(j));

                // Add a <br> tag
                extensionDiv.appendChild(document.createElement("br"));
            }

            moduleDiv.appendChild(extensionDiv);

            // Disable suboptions if main option is unchecked
            // Generated by ChatGPT
            moduleCheckbox.addEventListener('change', function() {
                let subOptions = this.closest('.main-option-group').querySelectorAll('.sub-option');
                if (this.checked) {
                    subOptions.forEach(subOption => {
                        subOption.disabled = false; // Enable sub-options
                    });
                } else {
                    subOptions.forEach(subOption => {
                        subOption.checked = false;  // Uncheck sub-options
                        subOption.disabled = true;  // Disable sub-options
                    });
                }
            });
        }

        checkboxList.appendChild(moduleDiv);
    }

    // Applying currently selected modules
    for (i of selectedModules) {
        console.log(i);
        // Check the module
        let moduleCheckbox = document.getElementById(i.name);
        moduleCheckbox.checked = true;
        
        // Run the event to enable/disable suboptions
        moduleCheckbox.dispatchEvent(new Event('change'));
        
        // Check all extentions
        for (j of i.extensions) {
            document.getElementById(i.name + ":" + j).checked = true;
        }
    }
}

generateOptions();


// Confirm button
// Generated by ChatGPT, edited
function confirmSelection() {
    // Extracting selected modules
    let modules = [];

    // Iterate over all main options
    document.querySelectorAll('.main-option').forEach(mainOption => {
        if (mainOption.checked) {
            let moduleName = mainOption.getAttribute('id');
            let subOptions = mainOption.closest('.main-option-group').querySelectorAll('.sub-option');
            let extensions = [];

            // Collect checked sub-options (extensions)
            subOptions.forEach(subOption => {
                if (subOption.checked) {
                    extensionName = subOption.getAttribute('id').split(':')[1];
                    extensions.push(extensionName);
                }
            });

            // Create new moduleInfo object and push it to the modules array
            modules.push(new moduleInfo(moduleName, extensions));
        }
    });

    // Apply the result
    window.setSelectedModules(window.gameName, modules);

    // Close self
    window.close();
}
