// Generated by ChatGPT

document.addEventListener("DOMContentLoaded", function () {
    // Particle effect initialization
    const canvas = document.getElementById("particle-canvas");
    const ctx = canvas.getContext("2d");

    let particles = [];

    function resizeCanvas() {
        canvas.width = window.innerWidth;
        canvas.height = window.innerHeight;
    }

    function createParticles() {
        particles = [];
        for (let i = 0; i < 80; i++) {
            particles.push({
                x: Math.random() * canvas.width,
                y: Math.random() * canvas.height,
                radius: Math.random() * 3 + 1,
                speed: Math.random() * 1 + 0.5,
                opacity: Math.random() * 0.5 + 0.3
            });
        }
    }

    function updateParticles() {
        for (let p of particles) {
            p.y -= p.speed;
            if (p.y < -p.radius) p.y = canvas.height + p.radius;
        }
    }

    function drawParticles() {
        ctx.clearRect(0, 0, canvas.width, canvas.height);
        ctx.fillStyle = "rgba(255, 255, 255, 0.8)";
        for (let p of particles) {
            ctx.globalAlpha = p.opacity;
            ctx.beginPath();
            ctx.arc(p.x, p.y, p.radius, 0, Math.PI * 2);
            ctx.fill();
        }
        requestAnimationFrame(drawParticles);
    }

    window.addEventListener("resize", resizeCanvas);

    resizeCanvas();
    createParticles();
    drawParticles();
});
